Switch to support both serialization frameworks (NOT WORKING)
Get a borrow checker problem:

	   Compiling rust-gron v0.1.0 (file:///development/gitarchives/rust-gron)
	error: borrowed value does not live long enough
	   --> src/json_struct.rs:63:14
	    |
	63  |             &Value::from_str(&rustc_serialize::json::encode(val).unwrap()).unwrap()
	    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ temporary value created here
	64  |         },
	    |         - temporary value only lives until here
	...
	186 | }
	    | - temporary value needs to live until here

Signed-off-by: Silvio Fricke <silvio.fricke@gmail.com>